### ISSUE TITLE
Messages do not render if container not in viewport

### ISSUE THREAD

**Issue by lancemccluskey** [paypal/paypal-messaging-components#463] opened 2021-03-18 16:20 UTC
Im using angular 1.8, and trying to render Messages in a dynamic field. After debugging for a bit I realized that messages wont render if the container you are trying to render them in is not within the viewport. It seems like the SDK sets HTML elements to 0 by 0 pixels if they are not visible. 

![Screen Shot 2021-03-18 at 11 23 11 AM](https://user-images.githubusercontent.com/40124399/111660814-7460fc00-87dc-11eb-9dca-d050bdf4f3a0.png)

As you can see from the screenshot, the `onRender` function is successfully called and the red rectangle Im trying to put the messages in is clearly not 0 by 0 pixels, but I still get the overflow warning message. I also get the hidden warning message from time to time (that one is intermittent).

My solution for now is to render the PayPal message at the top of the page and then move it where I need it. PayPal should look into a fix though.

**Comment by Seavenly** [comment] 2021-03-19 15:12
Hey Thomas. Sorry to hear that you're running into this issue. Thanks for providing some background information. We constantly strive to provide a robust module geared to meet as many use-cases as possible so we want to try and help see what's going on. We do check to ensure that our messages are fully visible to the consumer when rendered, which does include a check against its location. I'm sure as you're aware, there are many different ways to layout a webpage so we do run into edge-cases from time to time. Would you be able to provide a reproducible example or a link to where our team could observe this issue? That would be greatly appreciated so that we can drill into the exact scenario you're facing.

**Comment by lancemccluskey** [comment] 2021-03-19 16:01
Im running it locally using ngrok, ill leave it running through the day while I work

**Comment by lancemccluskey** [comment] 2021-03-19 16:11
If its helpful, it looks like the warnings are coming from [this](https://github.com/paypal/paypal-messaging-components/blob/develop/dist/bizcomponents/js/messaging.js) file within the below function where an `IntersectionObserver` is instantiated.

```javascript
$t = Bt("__intersection_observer__", (function() {
                return h.resolve(void 0 === window.IntersectionObserver ? Ot("https://polyfill.io/v3/polyfill.js?features=IntersectionObserver") : void 0).then((function() {
                    return h.all([Vt, Kt])
                })).then((function() {
                    var e = function(e) {
                        for (var n = Kn(e).innerHeight, t = [], r = e;
                            (null == (o = r) ? void 0 : o.parentNode.nodeType) === Node.ELEMENT_NODE;) {
                            var o;
                            t.push(r.parentNode), r = r.parentNode
                        }
                        return Nn()(t.reverse(), (function(e, t, r) {
                            var o = e.offsetHeight,
                                i = r[t + 1];
                            return o > n || i && i.offsetHeight < o && it(e.parentNode, e)
                        }))
                    }(kt.messagesMap.keys().next().value);
                    return new IntersectionObserver((function(n, t) {
                        var r = kt.messagesMap;
                        n.forEach((function(n) {
                            var o, i = n.target,
                                a = i.parentNode.parentNode,
                                s = (r.get(a) || {}).state;
                            if (null != s && s.renderStart) {
                                var c, u = a.getAttribute("data-pp-id"),
                                    l = Number(i.getAttribute("data-width")),
                                    d = Number(i.getAttribute("data-height")),
                                    f = It() - s.renderStart;
                                0 === (null == (o = n.rootBounds) ? void 0 : o.width) && 
                                0 === n.rootBounds.height && 
                                (c = it(e, n.target)), (n.intersectionRatio < .9 || Math.ceil(n.boundingClientRect.width) < l) && 
                                !c ? 
                                    ("smallest" === a.getAttribute("data-pp-style-preset") ? (Yt.warn(s.renderComplete ? "update_hidden" : "hidden", {
                                        description: "PayPal Message has been hidden. Fallback message must be visible and requires minimum dimensions of " + l + "px x " + d + "px. Current container is " + n.intersectionRect.width + "px x " + n.intersectionRect.height + "px.",
                                        container: a,
                                        index: u,
                                        duration: f
                                    }), Yt.track({
                                        index: u,
                                        et: "CLIENT_IMPRESSION",
                                        event_type: "message_hidden"
                                    }), s.renderComplete = !0, delete s.renderStart) : (a.setAttribute("data-pp-style-preset", "smallest"), Yt.warn(s.renderComplete ? "update_overflow" : "overflow", {
                                        description: "PayPal Message attempting fallback. Message must be visible and requires minimum dimensions of " + l + "px x " + d + "px. Current container is " + n.intersectionRect.width + "px x " + n.intersectionRect.height + "px.",
                                        container: a,
                                        index: u,
                                        duration: f
                                    })), i.style.setProperty("opacity", "0", "important"), i.style.setProperty("pointer-events", "none", "important"), t.unobserve(i)) : (i.style.setProperty("opacity", 1), i.style.setProperty("pointer-events", null), Yt.info(s.renderComplete ? "update_visible" : "visible", {
                                        index: u,
                                        duration: f
                                }), s.renderComplete = !0, delete s.renderStart, t.unobserve(i))
                            } else t.unobserve(i)
                        }))
                    }), {
                        root: e
                    })
                }))
            }));
```

**Comment by lancemccluskey** [comment] 2021-03-19 16:12
Specifically, it looks like this line
```javascript
(n.intersectionRatio < .9 || Math.ceil(n.boundingClientRect.width) < l) && !c
```
controls wether to hide the message and console log a warning or not.

**Comment by Seavenly** [comment] 2021-03-19 16:31
Unfortunately, we're unable to visit `ngrok` URLs. 😞  But it looks like you're trying to place a message in your cart. Does that cart just appear, or does it slide in from the side? You've zeroed in on the correct spot where we are determining whether or not to hide a message and the message today must reside within the bounds of the root webpage. So anything considered off to the side of the page is hidden. We do this because we must aggressively check whether or not our message is entirely visible to the consumer when rendered.

**Comment by lancemccluskey** [comment] 2021-03-19 17:36
It slides in on the real site, but when developing it just appears already in an open state.

**Comment by Seavenly** [comment] 2021-03-19 17:47
So when the page loads the cart is showing and visible by default? If that is the case are you able to share the cart container styles so that I can try to reproduce a little sample locally?

**Comment by lancemccluskey** [comment] 2021-03-19 18:07
Yeah they are, these are the cart styles when open:
```css
.cartDrawerOpen_km1mdn {
    transition: all 0.3s ease-in-out 0s;
    transform: translateX(0px);
    box-shadow: rgb(0 0 0 / 20%) 0px 0px 4px 2px;
}
```

Heres the overall cart drawer:
```css
.cartDrawer_1vgp48s {
    background-color: rgb(244, 244, 244);
    color: initial;
    width: 320px;
    height: 100vh;
    position: fixed;
    right: 0px;
    top: 0px;
    transition: all 0.3s ease-in-out 0s;
    transform: translateX(320px);
    z-index: 2147483641;
    overflow: hidden;
    display: flex;
    flex-flow: column;
    justify-content: stretch;
}
```

**Comment by lancemccluskey** [comment] 2021-03-19 18:15
One question thats been bugging me is why cant I just fix the issue by using a timeout? Even setting it to something crazy like 2 seconds wont work before trying to render the Messages

**Comment by Seavenly** [comment] 2021-03-19 19:54
Here is the example I put together from the styles you shared: https://gist.github.com/Seavenly/189d403d617e55ca389ba966199cd48c

The message appears to render ok. However, I can see that you're likely using `translateX()` to shift/animate the cart and when I adjust that value to shift the cart over then the message will hide on render because we are detecting that the message has rendered with partial to no visibility.

**Comment by lancemccluskey** [comment] 2021-03-19 20:58
Ok thanks for that! You're probably right about us using translateX(). I'll check and if so I'll try to find an alternative

**Comment by Seavenly** [comment] 2021-03-22 14:14
I've updated the gist to include a simple example of displaying the message the first time the cart opens. The message today will only hide when it first tries to render, so opening and closing the cart will not affect the message after it successfully renders. This may be a solution for you.

We are also looking into better supporting this scenario natively without the need for delaying the render. No exact ETA, but hopefully within a couple of weeks or so.

**Comment by lancemccluskey** [comment] 2021-03-22 15:46
So I can get the message to render at the top of the cart drawer, but not on the bottom beneath the PayPal buttons. Why are the PayPal buttons rendering without issue? Surely it matters if they are visible to the end user also.

![Screen Shot 2021-03-22 at 10 45 27 AM](https://user-images.githubusercontent.com/40124399/112017547-b7ccaa80-8afb-11eb-935b-b47b990f5cbe.png)


I tried rendering the message all over, but it still only renders on the top for some reason. Im looking at the other css and dont see any reasons that would cause it to hide.

**Comment by lancemccluskey** [comment] 2021-03-22 15:49
![Screen Shot 2021-03-22 at 10 48 27 AM](https://user-images.githubusercontent.com/40124399/112017996-23af1300-8afc-11eb-8a46-e478db1ff09c.png)

In this screenshot, you can see at the bottom that I copied the same div from the top with the cyan borders but it wont render. The bottom most cyan div and top have the exact same styles so idk why they are not showing

**Comment by lancemccluskey** [comment] 2021-03-22 15:50
The only thing I can think of is the logic that determines if the message is visible is incorrect.

**Comment by Seavenly** [comment] 2021-03-22 17:02
That may be the case and we would like to figure out what's going on, but I think we will need a more specific reproducible example if you're able to provide one so that we can drill into the exact issue you're seeing.

**Comment by lancemccluskey** [comment] 2021-03-22 18:13
![Screen Shot 2021-03-22 at 1 00 32 PM](https://user-images.githubusercontent.com/40124399/112036408-96c18500-8b0e-11eb-828c-de989d2425a4.png)

nvm its def something on our end. I just deleted all the css we are using and the messages are all rendering correctly. Thanks for helping me out though! Really appreciate it!

**Comment by Seavenly** [comment] 2021-03-22 19:26
No problem! My pleasure. I'll close this for now, but please feel free to open up another issue if you feel you've found another bug.

**Closed by Seavenly** 2021-03-22 19:26 UTC
