### ISSUE TITLE
Modifying viewport tag breaks layout

### ISSUE THREAD

**Issue by klase** [paypal/paypal-messaging-components#981] opened 2023-09-08 12:29 UTC
We're unable to use this component due to how the modal is modifying the viewport meta tag of our site. It removes viewport-fit=cover meaning css env vars like safe-area-inset stop working resulting in the close button becoming inaccessible.

<img width="245" alt="Screenshot 2023-09-08 at 13 27 55" src="https://github.com/paypal/paypal-messaging-components/assets/1711650/71d3328f-1352-44c6-b44b-01c9d0bdcbda">

**Comment by Seavenly** [comment] 2023-09-08 15:00
Hi @klase. I'm having trouble trying to reproduce the issue locally. Would you be able to provide a small reproducible example that might help me see the issue?

**Comment by monti-star** [comment] 2023-09-11 22:48
Hi @klase can you please provide a reproducible example, otherwise we will close this ticket as unable to reproduce.

**Comment by devchristina** [comment] 2023-09-13 22:15
No response received. Closing this issue without action. If this continues to be a problem, please re-open this issue and provide the information requested.

**Closed by devchristina** 2023-09-13 22:15 UTC
