### ISSUE TITLE
PayPal message has been hidden

### ISSUE THREAD

**Issue by aksenovroma** [paypal/paypal-messaging-components#677] opened 2021-11-22 09:07 UTC
Hi guys,

I'm trying to render the Paypal banner on Salesforce Community site. Sometimes the banner is not displayed on the page and the console shows a warning with this description - "PayPal Message has been hidden. Message must be visible and requires minimum dimensions of 0px x 0px. Current container is 0px x 0px.". But the container is the right size to display the banner. The banner rendering function works every time, regardless of whether the message is rendered or not. This can be seen from the message in the console – "onRender triggered".

The code for displaying the banner is given below:

```
paypalCheckoutInstance.loadPayPalSDK({
  components: 'messages',
  currency: 'USD',
  intent: 'authorize',
  'enable-funding': 'paylater',
  dataAttributes: {
    amount: '123.00'
  },
  commit: true
}).then(() => {
  paypal.Messages({
    amount: '123.00',
    currency: 'USD',
    style: {
      ratio: '20x1',
      layout: 'flex',
      color: 'blue'
    },
    onRender: function() {
      console.log('onRender triggered');
    }
  }).render('#paypal-banner');
```

Successful banner display:

![visible_element_1](https://user-images.githubusercontent.com/36088497/142833181-711634d2-6bc2-4e07-abae-516a682fd8b6.png)
![visible_element](https://user-images.githubusercontent.com/36088497/142833186-44fc4f52-e00f-43fa-8b18-4418229250a7.png)

Hiding the banner:

![hidden_element_1](https://user-images.githubusercontent.com/36088497/142832236-0aea05bf-1070-4a1d-87b2-c315033e513d.png)
![hidden_element](https://user-images.githubusercontent.com/36088497/142832242-26a54aad-50ab-41d9-8837-8a2596f8d0a5.png)

I can provide login information if you need to test the behavior yourself.

**Comment by rforsy1** [comment] 2021-11-22 15:38
Hi @aksenovroma, Are you using one of PayPal's Salesforce Commerce Cloud plugins? If so, could you provide the type and version number (i.e. PayPal B2C version 21.1.0, Braintree B2C version 21.2.0, etc.)?

**Comment by aksenovroma** [comment] 2021-11-22 17:53
Hello @rforsy1. I just use PayPal JavaScript SDK to render messages, no other PayPal's plugins.

**Comment by jadutter** [comment] 2021-11-22 18:09
Hi @aksenovroma, can you provide us a link (and/or login info) so that I can take a look at the web page where the error is occurring?

**Comment by aksenovroma** [comment] 2021-11-23 07:31
Hi @jadutter. You can test this behavior on our site by going to any category, such as "Coffee Accessories". You may have to refresh the page several times to see the wrong behavior

Site URL:  [(https://sandbox-efficiency-data-1095-dev-ed-17d37af6ef9.cs18.force.com/DefaultStore/s/)]
Username: test_user@b2ble-dev.nov 
Password: Test2021

**Comment by jadutter** [comment] 2021-11-23 17:56
@aksenovroma There appears to be some bad interaction occurring between the framework the page is using, and the paypal messaging components [observer](https://github.com/paypal/paypal-messaging-components/blob/develop/src/utils/observers.js). The observer is meant to ensure the messaging component renders only if there is space available to show the banner. 

If I load the webpage with a view size of 100px by 800px, then the custom element `.ui-widget c-pay-pal-banner` is offscreen, and the framework seems to give no space to the messaging component. 

If I instead scroll to the bottom of the webpage and reload, I can see the framework show a spinner that becomes the paypal messaging banner.

**Comment by jadutter** [comment] 2021-11-23 18:58
@aksenovroma I've confirmed there is an issue with paypal-messaging-components incorrectly determining the message should not be visible when the iframe is not currently in the current scroll view.

**Comment by jadutter** [comment] 2021-11-23 22:31
I have [opened a pull request](https://github.com/paypal/paypal-messaging-components/pull/679) to resolve this issue with messages in iframes being set to hidden when outside the viewport.

**Comment by aksenovroma** [comment] 2021-11-24 15:16
Thank you. I'll wait for updates from your side.

**Comment by devchristina** [comment] 2023-09-22 20:51
Due to competing priorities, we will close this issue with "not planned". If this feature is a high priority by yourself or any future devs, we can re-open and look into the effort.

**Closed by devchristina** 2023-09-22 20:51 UTC
