### ISSUE TITLE
Messages are not visible in angular 8 SPA

### ISSUE THREAD

**Issue by tworekm** [paypal/paypal-messaging-components#403] opened 2020-12-18 15:22 UTC
Hello guys,

I have problem with messages in angular 8 SPA app. When I am trying to render credit banner with sandbox credentials then nothing happens. render() function is triggered after paypal script is loaded. Also render() success callback is triggered but onRender() not. When I am using LIVE credentials then onRender is also triggered but in browser console I can find message like: 
`paypal_messages_overflow: PayPal Message attempting fallback. Message must be visible and requires minimum dimensions of 0px x 0px. Current container is 0px x 0px.`

Credit banner is visible for fraction of second and container has correct dimensions. I have no idea what I am doing wrong because this implementation is working on non SPA app.

This is how banner is rendered after getting event with script loaded confirmation: 

> renderPayPalCreditBanner(payPalConfig) {
>         paypal.Messages({
>             amount: '123',
>             style: {
>                 layout: payPalConfig.payPalStyleLayout,
>                 logo: {
>                     type: payPalConfig.payPalTextLayoutType,
>                 },
>                 text: {
>                     size: payPalConfig.payPalTextSize,
>                     color: payPalConfig.payPalTextColor,
>                 },
>                 color: payPalConfig.payPalLayoutColor,
>                 ratio: payPalConfig.payPalFlexStyleRatio
>             },
>             onRender: (data)=> {
>                 console.log('onRender',data);
>             }
>         }).render('#paypal-messages-container').then(function(success){
>                 console.log('success', success);
>         }, function(error){
>                 console.log('error', error);
>         });
>     }

and script: 
https://www.paypal.com/sdk/js?client-id=CLIENT_ID&currency=EUR&commit=true&components=buttons,messages

**Comment by Seavenly** [comment] 2021-03-22 19:50
Hello @tworekm. Apologies for the late response. Is this issue still relevant? If so would you be able to provide a screenshot of what your webpage looks like and where the message should be displaying? And would you be able to reproduce the issue in an example that we could look at?

**Comment by Seavenly** [comment] 2021-04-05 15:44
Closing, but please feel free to open up a new issue again in the future.

**Closed by Seavenly** 2021-04-05 15:44 UTC
